<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Manager.aspx.cs" MasterPageFile="~/MasterPage/Kalendarz.master" Inherits="Kalendarz.Manager" %>

<asp:Content 
    ID="Content1" 
    ContentPlaceHolderID="ContentPlaceHolder1" 
    Runat="Server">

    <div>
        <asp:Button ID="btnPowrot" runat="server" Text="Powrót" OnClick="btnPowrot_Click" />
        <asp:GridView ID="GridView1" runat="server" 
            AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" 
            DataSourceID="SqlDataSource1" AllowPaging="True" AllowSorting="True" 
            AutoGenerateColumns="False" CellPadding="4" DataKeyNames="Id" 
            ForeColor="#333333" GridLines="None">

            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:CheckBoxField DataField="Admin" HeaderText="Admin" SortExpression="Admin" />
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        
        <asp:SqlDataSource ID="SqlDataSource1" 
            runat="server" 
            ConnectionString="<%$ ConnectionStrings:DaneUzytkownikow %>" 
            SelectCommand="SELECT ID, UserName, Email, Admin, Password FROM [tblUsers]"
            UpdateCommand="UPDATE tblUsers SET UserName=@UserName,
                           Email=@Email, Admin=@Admin, Password=@Password WHERE ID=@ID"
            DeleteCommand="DELETE tblUsers WHERE Id=@Id">

        </asp:SqlDataSource>

    
    </div>
    </asp:Content>
   
